%%{init: { 'theme': 'base', 'themeVariables': { 'actorBackground':'#f3f4f6' }}}%%
flowchart LR
  subgraph Actors
    direction TB
    SA([Super-admin])
    AP([Auth Provider])
  end

  subgraph UseCases
    direction TB
    AUTH((Authenticate))
    OAD((Open Admin Dashboard))
    AO((Approve Organizations))
    MU((Manage Users))
    MD((Manage Donations))
    MA((Manage Actions))
    RP((Review Participations))
    MPM((Review Platform Metrics))
    IOQ((Review Pending Organization))
    EUR((Edit User Role))
    IAD((Inspect Action Detail))
  end

  SA --> OAD
  SA --> AO
  SA --> MU
  SA --> MD
  SA --> MA
  SA --> RP
  SA --> MPM

  OAD -.->|<<include>>| AUTH
  AO -.->|<<include>>| AUTH
  MU -.->|<<include>>| AUTH
  MD -.->|<<include>>| AUTH
  MA -.->|<<include>>| AUTH
  RP -.->|<<include>>| AUTH
  MPM -.->|<<include>>| AUTH

  AO -.->|<<include>>| IOQ
  MU -.->|<<include>>| EUR
  MA -.->|<<include>>| IAD

  AP --> AUTH